type Address {
  uid: ID!
  address: String!
  city: String!
  province: String!
  zipCode: String!
  country: String!
  coordinates: String
}

input AddressInput {
  address: String!
  city: String!
  province: String!
  zipCode: String!
  country: String!
  coordinates: String
}

type Query {
  getAddress(uid: ID): Address
}

type Mutation {
  
  createAddress(
    address: String!
    city: String!
    province: String!
    zipCode: String!
    country: String!
    coordinates: String
  ): Address

  updateAddress(
    uid: ID!
    address: String!
    city: String!
    province: String!
    zipCode: String!
    country: String!
    coordinates: String
  ): Address
  
  deleteAddress(uid:ID!): Address
}