enum VerificationStatus {
    PENDING
    VERIFIED
    DECLINED
  }

  # This "clinic" type defines the queryable fields for every clinic in our data source.
type Clinic {
  uid: ID!
  name: String!
  roomNumber: String
  address: String!

  licence_no: String!
  experience: Int!
  rating: Int
  clinic_verification_status: VerificationStatus
  about: String
  bio: String
}

  # The "Query" type is special: it lists all of the available queries that
  # clients can execute, along with the return type for each. In this
  # case, the "clinic" query returns an array of zero or more clinic (defined above).

type Query {
  getClinic(uid: ID): [Clinic]
}

type Mutation {
  createClinic(
    address: String!
    firstName: String!  
    lastName: String!
    email: String!
    password: String!
    sex: String!
    # birthdate: Date
    phoneNumber: String
    weight: Float
    height: Float
    civilStatus: String
    nationality: String
    isClinic: Boolean
    licenceNo: String!
    experience: Int!
    rating: Int
    verificationStatus: VerificationStatus
    about: String
    bio: String
  ): Clinic

  updateClinic(
    address: String!
    firstName: String!
    lastName: String!
    email: String!
    password: String!
    sex: String
    # birthdate: Date
    phoneNumber: String
    weight: Float
    height: Float
    civilStatus: String
    nationality: String
    isClinic: Boolean
    licenceNo: String!
    experience: Int!
    rating: Int
    verificationStatus: VerificationStatus
    about: String
    bio: String
  ): Clinic

  deleteClinic(uid: ID!): Clinic
}