
interface User {
  uid: ID!
  firstName: String!
  MiddleName: String
  lastName: String!
  email: String!
  password: String!
  # role: Role!
  # createdAt: DateTime
  # updatedAt: DateTime
}

type Admin implements User {
  uid: ID!
  firstName: String!
  MiddleName: String
  lastName: String!
  email: String!
  password: String!
  # role: Role!
  # createdAt: DateTime
  # updatedAt: DateTime
}

type Query {
  getUser(uid: ID!): User!
  getAllUser: [User!]
  viewer: User
}

type Mutation {
  signUp(
    firstName: String!
    middleName: String
    lastName: String!
    # email: EmailAddress!
    password: String!
    # role: Role!
  ): User!

  updateUser(
    firstName: String!
    MiddleName: String
    lastName: String!
    password: String!
    # role: Role!
  ): User!

  deleteUser(uid: ID!): User!

  signIn(email: String!, password: String!): User!
}



